### ISSUE TITLE
MESH pages show meshv:Descriptor instead of the most specific type

### ISSUE THREAD

**Issue by VladimirAlexiev** [HHS/meshrdf#120]
Find some `meshv:GeographicalDescriptors` using this query
```sparql
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>

select * {
  ?x a meshv:GeographicalDescriptor; rdfs:label ?lab
} limit 10
```
Examine one of them eg https://id.nlm.nih.gov/mesh/D008922. It shows the type is `Descriptor` rather than the more specific `GeographicalDescriptor`.
Clicking on "More types..." doesn't show any more types.

If you download https://id.nlm.nih.gov/mesh/D008922.n3 or https://id.nlm.nih.gov/mesh/D008922.json-ld, you see the more specific type as expected.

**Comment by danizen** [comment]
This does not affect TopicalDescriptors. Have previous versions of Lodestar at EBI had this same issue?

**Comment by danizen** [comment]
@VladimirAlexiev , I see the issue now.  The landing page will query https://id.nlm.nih.gov/mesh/servlet/explore/resourceTypes?uri=http://id.nlm.nih.gov/mesh/D008922 to get the type data, and then constructs without an awareness of specific type, and so the order is the issue.

It isn't properly semantic, but the simplest thing that could work is to prefer the longest match that begins with "http://id.nlm.nih.gov/mesh".

**Comment by VladimirAlexiev** [comment]
Without reasoning, rdf:type should return the most specific class. Only with rdfs:subClass reasoning it will return also the superclasses

**Comment by danizen** [comment]
Yes, I turned off inference but kept my test code.  Now it is just a matter of CI/CD running through its paces and such.

**Comment by danizen** [comment]
This should now be fixed, thanks for helping out.
