### ISSUE TITLE
provide a VOID file

### ISSUE THREAD

**Issue by VladimirAlexiev** [HHS/meshrdf#121]
Provide a semantic description of the dataset in the form of a VOID file.
See eg http://vocab.getty.edu/doc/#Descriptive_Information, which uses the VOID, DCAT and ADMS ontologies to provide comprehensive description.
It would be nice if you use the VOID ontology (which is mandatory for RDF datasets) and DCAT ontology (which is popular for dataset portals); ADMS is less popular.

The recommended locations for VOID deployment are https://id.nlm.nih.gov/.well-known/void and https://id.nlm.nih.gov/void.ttl.
- Getty implements both locations (with a redirect), so you can see the Getty VOID at http://vocab.getty.edu/.well-known/void or http://vocab.getty.edu/void.ttl.
- Thus far https://id.nlm.nih.gov/ includes only MESH data (and redirects to https://id.nlm.nih.gov/mesh/). If in the future you include other NLM data, you'd need to enrich or split the VOID.
- Make sure you include license information.

Note: this query 
```sparql
SELECT DISTINCT ?g {GRAPH ?g { ?s ?p ?o }}
```
returns https://id.nlm.nih.gov/mesh/void amongst its results, but the void URL does not resolve.

This query
```sparql
select * {graph <https://id.nlm.nih.gov/mesh/void> {?s ?p ?o}}
```
returns no triples.

Thanks for all your efforts!!!

**Comment by VladimirAlexiev** [comment]
- Also load the MESH triples to the triplestore, so they can be queried
- The VOID can also be used to register MESH RDF on the datahub.
  - https://datahub.io/search?q=mesh finds nothing
  - https://old.datahub.io/dataset?q=mesh finds 21 datasets, amongst them https://old.datahub.io/dataset/bio2rdf-mesh that claims to have VOID but http://download.bio2rdf.org/current/mesh/bio2rdf-mesh.nq doesn't resolve.

http://bio2rdf.org/sparql returns some datasets:
```sparql
select * {?x a void:Dataset}
```
but they got no data except type
```sparql
select * {<http://rdf.disgenet.org/v3.0.0/void/pubmed> ?p ?o}
```

**Comment by bushmanb** [comment]
We have a VOID file for MeSH RDF.  It is located at ftp://ftp.nlm.nih.gov/online/mesh/rdf/void_1.0.0.ttl.  Please let us know if you have any further questions..

**Comment by danizen** [comment]
@VladimirAlexiev , can you expand on what you mean?  In addition to what Barbara says above, https://id.nlm.nih.gov/mesh/void.ttl is also available, and a query through the sparql endpoint will also produce those triples:

```sparql
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?s ?p ?o 
WHERE {
  ?s a <http://rdfs.org/ns/void#Dataset>
  OPTIONAL {
    ?s ?p ?o
  }
}
```

**Comment by danizen** [comment]
@bushmanb , the issue is that https://id.nlm.nih.gov/mesh/void is a result but does not resolve.   We have https://id.nlm.nih.gov/mesh/void.ttl, but that is not the same - I can address this easily.

**Comment by VladimirAlexiev** [comment]
Thanks! I didn't know about this location.

But the recommended locations are as listed above (the Getty reference has links to the specs). A sem.crawler would not know to look under the /mesh path.

I'll make specific suggestions about the content in 2 weeks
- add stats, such as triples and entities
- describe the historic datasets as Distributions and add some version info and prev links
- add license

Would you please consider registering the dataset on datahub.io?

**Comment by danizen** [comment]
@VladimirAlexiev , thank you. Does datahub.io act as a registry of datasets or does it attempt to import the data?  Our data has too many triples to be easily imported into bioportal, at least so far.

**Comment by danizen** [comment]
@VladimirAlexiev , in a prior comment, you mentioned trying this query:

```sparql
select * {graph <https://id.nlm.nih.gov/mesh/void> {?s ?p ?o}}
```

The issue there is that you used `https` rather than `http`.   Nevertheless, it must resolve.

**Comment by danizen** [comment]
This should now be fixed; please feel free to open another issue if you have suggestions on the contents of the void file.

**Comment by VladimirAlexiev** [comment]
@danizen datahub is just a registry. You have to submit your dataset and the void helps with the submission. 

It's also the basis of the famous lod-cloud.org diagram. To get included you need to submit rich metadata (eg see Getty AAT as an example) and have links from/to your dataset (I believe MESH has many incoming links as it's a foundational thesaurus)
