### ISSUE TITLE
Need tree view for concept hierarchies

### ISSUE THREAD

**Issue by micheldumontier** [HHS/meshrdf#15]
The current interface does not show tree views for concept hierarchies.  

you should consider something like: http://bioportal.bioontology.org/ontologies/RH-MESH?p=classes&conceptid=root

**Comment by nvariant** [comment]
That interface is build-able by a user using the RDF data provided, using tree numbers to navigate. The emphasis for the MeSH in RDF project is to make the data available using RDF, which is different from making an interface 

We will take your comment under consideration as we we update and modify our MeSH browser interface. 

Thank you for bringing this up.

John Kilbourne MD
Head, Medical Subject Headings
