### ISSUE TITLE
Year parameter does not query specific years of MeSH

### ISSUE THREAD

**Issue by AlastairKelly** [HHS/meshrdf#164]
I'm a SPARQL novice, so I'll acknowledge upfront that it's entirely possible that I am the issue.  

We have a dataset that includes a list of MeSH terms from 2018. I am using the SPARQL endpoint to retrieve the IDs and tree numbers for these. Some MeSH terms have changed since then, so I need my queries to run against the 2018 version of MeSH, rather than the current one. According to the documentation [here](https://hhs.github.io/meshrdf/sparql-and-uri-requests.html), the year parameter should allow me to do that. However, this doesn't seem to be working for me. Using this parameter does not change the results I get from any query. It seems that the parameter is being ignored. Is this parameter actually not supported, or am I doing something wrong? 

For example, our data contains the descriptor "Infection", which was used until 2019. In 2020, the preferred term was changed to the plural form "Infections", so the default search for "infection" does not bring up a match. I expected adding the "&year=2018" to this query would return a match, since "infection" should be present in MeSH 2018, but it returns the same empty set. These URLS and my SPARQL query are below. The same test performed with "Pangolins" retrieves the identifiers regardless of the year specified, despite the fact that it was just added to MeSH 2021 and did not exist in MeSH 2018. 

**Infection search without a year specified:** 
https://id.nlm.nih.gov/mesh/sparql?query=PREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%20PREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%20PREFIX%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%20PREFIX%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%20PREFIX%20meshv%3A%20%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2Fvocab%23%3E%20PREFIX%20mesh%3A%20%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2F%3E%20PREFIX%20mesh2018%3A%20%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2F2018%2F%3E%20%20%20SELECT%20%3FtreeNum%20%3Fidentifier%20FROM%20%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%3E%20WHERE%20%7B%20%20%20%20%3Fterm%20a%20meshv%3ADescriptor.%20%20%20%20%3Fterm%20rdfs%3Alabel%20%3Falabel.%20%20%20%20%3Fterm%20meshv%3AtreeNumber%20%3FtreeNum%20.%20%20%20%20%3Fterm%20meshv%3Aidentifier%20%3Fidentifier.%20%20%20%20FILTER%20regex(%3Falabel%2C%20%22%5Einfection%24%22%2C%20%22i%22)%20%7D&format=TSV&inference=true&offset=0&limit=1000

**With 2018 specified:** 
https://id.nlm.nih.gov/mesh/sparql?query=PREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%20PREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%20PREFIX%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%20PREFIX%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%20PREFIX%20meshv%3A%20%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2Fvocab%23%3E%20PREFIX%20mesh%3A%20%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2F%3E%20PREFIX%20mesh2018%3A%20%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2F2018%2F%3E%20%20%20SELECT%20%3FtreeNum%20%3Fidentifier%20FROM%20%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%3E%20WHERE%20%7B%20%20%20%20%3Fterm%20a%20meshv%3ADescriptor.%20%20%20%20%3Fterm%20rdfs%3Alabel%20%3Falabel.%20%20%20%20%3Fterm%20meshv%3AtreeNumber%20%3FtreeNum%20.%20%20%20%20%3Fterm%20meshv%3Aidentifier%20%3Fidentifier.%20%20%20%20FILTER%20regex(%3Falabel%2C%20%22%5Einfection%24%22%2C%20%22i%22)%20%7D&format=TSV&inference=true&offset=0&limit=1000&year=2018

**My original SPARQL query:**

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX mesh: <http://id.nlm.nih.gov/mesh/>
PREFIX mesh2018: <http://id.nlm.nih.gov/mesh/2018/> 

SELECT ?treeNum ?identifier
FROM <http://id.nlm.nih.gov/mesh>
WHERE {
   ?term a meshv:Descriptor.
   ?term rdfs:label ?alabel.
   ?term meshv:treeNumber ?treeNum .
   ?term meshv:identifier ?identifier.
   FILTER regex(?alabel, "^infection$", "i")
}

**Comment by AlastairKelly** [comment]
Nevermind, I just spotted my own error in the query--no year specified in the FROM clause--as soon as I hit "Comment."

**Comment by danizen** [comment]
I am also dissatisfied with this, because users must be "very careful" about which graph they are querying.  Another thing you should be aware of is that when you are querying the "current" graph, you have to add queries on meshrdf:active to get only active MeSH.   So, if you want your queries to work against both the '"current" graph and the previous years graph, then you should "subtract" inactive records.   You can see in the [lookup queries](https://github.com/HHS/meshrdf/blob/develop/webui/src/main/resources/lookup-queries.yaml) file some of my own work-arounds:

```sparql
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
    PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
    PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
    PREFIX bif: <bif:>
    
    SELECT ?resource ?label
    FROM <http://id.nlm.nih.gov/mesh>
    WHERE {
      ?resource a meshv:Descriptor .
      ?resource rdfs:label ?label .
      ?label bif:contains ?boundstar .
      BIND(LCASE(STR(?label)) AS ?lowerlabel) .
      FILTER(?lowerlabel = ?bound) .
      MINUS {
        ?resource meshv:active "false"^^xsd:boolean .
      }
    } ORDER BY ?label
```

You can then use regexp or Jena query transformations to change the the query FROM clause.

**Comment by AlastairKelly** [comment]
Ugh, thanks for the heads up on that!
I thought my familiarity with SQL would make SPARQL easy to pick up, but the similarity is much more limited than I hoped. I find many of the logical mechanisms very unintuitive, so I appreciate all the examples you have provided.

**Comment by danizen** [comment]
No problem.   SPARQL is certainly different.

The killer feature is "inference", which can almost magically calculate things for you based on rules.  Even popular graph softwares such as Neo4J don't abstract the inference into a language of relationships as much as RDF.
