### ISSUE TITLE
Concept vs. Descriptor

### ISSUE THREAD

**Issue by bushmanb** [HHS/meshrdf#17]
From Stanford (NCBO): We are confused about what the basic “node” of the system should be. It appears to be “concept” in some places and “descriptor” in others. Are there really meant to be two interlinked kinds of hierarchies? For example, in BioPortal we show relations among a single “type of thing”. Often this is “class”. For skos it is skos:concept. It is unclear to us which is the “main thing here”, concept or descriptor. Also, would it make sense for us to create two BioPortal ontologies, one for concepts and one for descriptors. This whole thing is confusing to us.

**Comment by danizen** [comment]
Closing this issue as it refers mostly to an internal discussion.
