### ISSUE TITLE
Swagger UI for MeSH API is down

### ISSUE THREAD

**Issue by piotr-gawron** [HHS/meshrdf#188]
It looks like MeSH API is down. When I've tried to open: https://id.nlm.nih.gov/mesh/swagger/ui I got:
```
Failed to load API definition.
Errors
Hide
 
Fetch error
undefined https://id.nlm.nih.gov/mesh/swagger/swagger.json
```

**Comment by danizen** [comment]
Yes, I can.    @piotr-gawron, it is actually the Swagger spec and UI that are done, following work to make Swagger UI more secure.   I tested the following API and it is working:

https://id.nlm.nih.gov/mesh/lookup/details?descriptor=D015242

**Comment by danizen** [comment]
@piotr-gawron, this should be fixed.

**Comment by piotr-gawron** [comment]
@danizen, thanks
