### ISSUE TITLE
Change meshv predicates to be more specific

### ISSUE THREAD

**Issue by bushmanb** [HHS/meshrdf#19]
We are proposing to make the adjustments to the following meshv predicate terms to clarify the relationships expressed in the MeSH RDF.  Unless stated all of the predicates will be non-transitive.  We would appreciate any feedback on these changes.

meshv:broader will become meshv:broaderConcept
meshv:narrower will become meshv:narrowerConcept
meshv:related will become meshv:relatedConcept
These changes are  to reflect the definition which states that these relationships exist between two concepts.

meshv:broaderTransitive will become meshv:parentTreeNumber
The change in this predicate is to reflect that it is used to relate Tree numbers and not descriptors or concepts.  This predicate will continue to be transitive.

In addition, we will be adding two new predicates
meshv:broaderDescriptor
meshv:broaderQualifier
These new predicates will be used to illustrate the relationships between descriptors and between qualifiers.

**Comment by micheldumontier** [comment]
Hi!
  i suggest that you map these to SKOS terminology, and there are also mappings for SIO:

http://semanticscience.org/resource/is-identical-to
http://semanticscience.org/resource/is-broader-than
http://semanticscience.org/resource/is-narrower-than
http://semanticscience.org/resource/is-similar-to
http://semanticscience.org/resource/is-related-to

**Comment by Klortho** [comment]
The changes Barbara described above are documented in the page of [release notes for the upcoming release](http://hhs.github.io/meshrdf/release-notes.html).

@micheldumontier, how would you suggest that the mappings be done? I'd guess that owl:sameAs would not be a good idea.

**Comment by Klortho** [comment]
@micheldumontier, if you respond, please do so over on [issue #12](https://github.com/HHS/meshrdf/issues/12), "Mappings to SKOS?".

I'm going to close this ticket.
