### ISSUE TITLE
Release date of the MeSH2024 RDF dataset 

### ISSUE THREAD

**Issue by filak** [HHS/meshrdf#211]
We have already received the translators data for MeSH 2024 and the desc2024.xml file.

For our translation workflow I need to get the RDF data - mesh.nt file - https://nlmpubs.nlm.nih.gov/projects/mesh/rdf/

Would you be so kind and let me know some date when the official mesh.nt file will be available for download ?

(I might try to convert it on my own but the XML files for the MeSH 2024 version have not yet been published - https://nlmpubs.nlm.nih.gov/projects/mesh/MESH_FILES/xmlmesh/).

**Comment by seibertpb** [comment]
Hello,
Currently we are working on testing and quality control testing of the MeSH 2024 files to include MeSH RDF. We anticipate the 2024 MeSH XML will be released Dec 4, 2023 and the 2024 MeSH RDF will be release NLT Dec 22, 2023.
/r
Peter Seibert
National Library of Medicine
