### ISSUE TITLE
Issues with running the script on MeSH 2024 data

### ISSUE THREAD

**Issue by filak** [HHS/meshrdf#212]
Firstly, thank you for all the hard work on making the transformation.

I have tried recently to run the script on MeSH 2024 in preparation for the 2025 version and I have observed some issues:

1. I had to disable the message "Warning: literal value that has leading or trailing whitespace" - as it was polluting the output

2. I have also replaced the related whitespace removal code with <xsl:strip-space elements="*"/>

3. I have updated all the XSL files to UTF-8 encoding

4. When running the script on the data there were some errors while converting supp2024.xml file - it seems the suppl.xsl is outdated. The Transformation rule: SCRClass does not have options for values 5 and 6 - so I added SCR_Population and SCR_Anatomy - though these are not yet defined in the vocabulary.owl

5. I do not know what the OASIS_CATALOG variable is used for - I have not found any mention of it in the docs - though the script works fine without setting it

Finally I have got the final mesh.nt.gz and I compared it to the official 2024 version and found some differences:

The whitespace in values in the official dataset - there is no leading or trailing whitespace in the new dataset - which is OK

6. The http://id.nlm.nih.gov/mesh/vocab#active triples are missing in the new dataset - **this is not OK**

7. The "inactive" items - http://id.nlm.nih.gov/mesh/vocab#active false - are missing completely - for example http://id.nlm.nih.gov/mesh/D013749 - these records are missing in the source XML - **how to get these records into the dataset ?**

I have pushed all the updates into the forked repo - https://github.com/filak/meshrdf/tree/fix-2024
 
Please, would you be so kind and give some advice on the issues - at least 6. and 7. - because I definitely need to have this data in the dataset.

**Comment by seibertpb** [comment]
Hello, I am taking a look at your issues with the 2024 MeSH RDF and will get you an update as to the issues you are seeing in the data. For future reference please submit future issues and bugs to https://support.nlm.nih.gov/ as we will be retiring the Github Issues section and directing all customer requests to our Help Desk for faster responses. I will update this issue when I have looked into the issues.

**Comment by filak** [comment]
Any updates on this?

**Comment by chandrakola** [comment]
We pushed changes.  SCR_Population and SCR_Anatomy are in feature/YearEndProcessing branch, I merged into master .
We identified a bug in triples creation for broaderDescriptor and broaderQualifier and fixed it.
Added new function to trim leading and trailing whitespace.

**Comment by chandrakola** [comment]
http://id.nlm.nih.gov/mesh/vocab#active (true or false) triple is missing. With 2025 data, I am able to see them again.

**Comment by filak** [comment]
Thank you. So is the MeSH 2025 XML version already available ?

**Comment by chandrakola** [comment]
It's not yet available for public. We are in testing phase. I am expecting our business team will get back to you regarding public availability.
Let me know if you need any more information, I am happy to pass on to business Support/Operation team at NLM.

**Comment by filak** [comment]
About the active state - in the MeSH XML 2023 or 2024 the obsolete descriptors are missing - so I am quite sure that you cannot get vocab#active=false - respectively all the records in the dataset are active - so you get only active=true.

How can you produce triples for a missing descriptor ?

**Unless your input files are different from the ones available to be downloaded officially**:

https://nlmpubs.nlm.nih.gov/projects/mesh/2023/xmlmesh/

https://nlmpubs.nlm.nih.gov/projects/mesh/MESH_FILES/xmlmesh/desc2024.xml

Here is an example of obsolete descriptor - removed in 2023:
https://id.nlm.nih.gov/mesh/D018290.html

I can see the data in the official mesh.nt:

```
<http://id.nlm.nih.gov/mesh/D018290> <http://id.nlm.nih.gov/mesh/vocab#active> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://id.nlm.nih.gov/mesh/vocab#TopicalDescriptor> .
<http://id.nlm.nih.gov/mesh/D018290> <http://www.w3.org/2000/01/rdf-schema#label> "[OBSOLETE] Cervical Intraepithelial Neoplasia"@en .
```

So is it possible to get the full MeSH XML files containing obsolete records ?

**Comment by seibertpb** [comment]
> Thank you. So is the MeSH 2025 XML version already available ?

Hello - we will be releasing the 2025 MeSH XML on Dec 4th 2024. Please keep an eye on https://www.nlm.nih.gov/databases/download/mesh.html
/r
Peter Seibert

**Comment by filak** [comment]
@seibertpb That's great news! 

However I still wonder how to get the obsolete MeSH items into the RDF dataset...

**Comment by filak** [comment]
I have tried to download the data today:

1. https://nlmpubs.nlm.nih.gov/projects/mesh/rdf/mesh.nt.gz 
- this is still 2024 full version - the same file I downloaded in January 2024
 
2. https://nlmpubs.nlm.nih.gov/projects/mesh/rdf/2025/mesh2025.nt.gz 
- this is the "year-namespaced" version of 2025 which contains only the active terms

So I am still waiting for the full and complete 2025 version.

Please @seibertpb when it will be made available ?

(I might create the 2025 RDF myself using your script but without the complete XML input this seems not possible...)
