### ISSUE TITLE
Redo how the uri-year-segment gets passed to the XSLTs

### ISSUE THREAD

**Issue by Klortho** [HHS/meshrdf#34]
Right now, the mesh-xml2rdf.sh script generates a dtd external subset with some XML entities defined.  Instead, I'm going to change it so that the year segment gets passed in as a string parameter.

**Comment by danizen** [comment]
How about using Getopt::Long to make it an optional parameter and to default to 2015?

**Comment by Klortho** [comment]
It's a shell script.  I didn't want to rewrite the whole thing in perl.  I just added a param to the xslts (I'd have had to do that anyway)

**Comment by danizen** [comment]
Ah - I see.   I didn't know how to do that and just use the sed of the prefixes file.   A parameter is better.
bash has getopts built-in.

**Comment by Klortho** [comment]
This fix is part of https://github.com/HHS/meshrdf/pull/32
