### ISSUE TITLE
Download links are down

### ISSUE THREAD

**Issue by developer4711** [HHS/meshrdf#59]
Hi all!

Could you please fix the download links?

Also the ftp service is not available, only for me??

Thanks in advance

**Comment by butlerj** [comment]
It works when I try it.  Please try again.
Thanks,
John

**Comment by danizen** [comment]
Can you be more specific about which download links are failing for you?

Thanks,
Dan Davis

**Comment by danizen** [comment]
@developer4711, I would like to close this issue.   Can you clarify whether these links are now working for you?
