### ISSUE TITLE
Accessing subclassof ?

### ISSUE THREAD

**Issue by bjonnh** [HHS/meshrdf#65]
Hi, 

I tried the "string search on 'infection". It works with your query editor. However, when I use rdflib (python), this query isn't working. I have to change the meshv:Descriptor to meshv:TopicalDescriptor to make it work.

Do you have any idea about why and how I could get that working on meshv:Descriptor ?

I also tried:

?d rdfs:subClassOf+ meshv:Descriptor .

in order to get any subclassof that, but it doesn't help neither.

**Comment by bjonnh** [comment]
Ok, for later reference to anyone:
I had to set inference=true in the parameters.

**Comment by danizen** [comment]
It is good to know  that this is working with rdflib.   You are using rdflib, rather than rdfalchemy, correct?   We would love to see sample code, perhaps we can add a sample code page for Python, Java, and Ruby at some later date.

**Comment by bjonnh** [comment]
Yes I use rdflib, here is a sample code using SPARQLWrapper.

```python
import rdflib
from SPARQLWrapper import SPARQLWrapper, JSON
import time

sparql = SPARQLWrapper("http://id.nlm.nih.gov/mesh/sparql")
sparql.addParameter('inference','true')
sparql.setReturnFormat(JSON)

queryString="""
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX mesh: <http://id.nlm.nih.gov/mesh/>
PREFIX mesh2015: <http://id.nlm.nih.gov/mesh/2015/>
PREFIX mesh2016: <http://id.nlm.nih.gov/mesh/2016/>

SELECT ?d ?dName ?c ?cName ?t ?v
WHERE { 
  ?d a meshv:Descriptor .
  ?d meshv:concept ?c .
  ?d ?t ?c .
  ?t rdfs:label ?v .
  ?d rdfs:label ?dName .
  ?c rdfs:label ?cName
  FILTER(REGEX(?dName,'stap','i') || REGEX(?cName,'stap','i')) 
}
"""

try :
   sparql.setQuery(queryString)
   tim = time.time()
   ret = sparql.query()
   print("Request time {} ms".format(1000*(time.time()-tim)))
except :
   print("Something is wrong")
out=ret.convert()

for line in out['results']['bindings']:
    print("{} - [{}] -> {}".format(line['cName']['value'],line['v']['value'],line['dName']['value']))
```

**Comment by danizen** [comment]
Thanks @bjonnh, I'll create an internal issue for sample API code in the documentation site.
