### ISSUE TITLE
Need MeSH label look up service

### ISSUE THREAD

**Issue by fallgrennj** [HHS/meshrdf#71]
Cataloging data will eventually be rendered as linked data.  A growing number of libraries are trying to prepare in advance for that change by inserting existing URIs for relationships and objects into their cataloging data now.

I am learning that the cataloging community could use a label-based search feature for MeSH RDF.  Our current cataloging tools do not have SPARQL querying capability and few, if any, catalogers have the knowledge to frame a SPARQL query themselves.  Catalogers want to be able to look up the MeSH label (D or D+Q) and have the correct MeSH RDF URI returned so it can be added to the cataloging data.  The MeSH browser doesn’t accommodate this use case because it doesn’t combine D+Q pairs.

**Comment by Pashj** [comment]
We were testing an RDF-MeSH based browser for a while, however I'm not sure whether OCCS is still working on it. Would that work for what you want?.

**Comment by danizen** [comment]
@fallgrennj  I think this issue should have gone to mesh-rdf.    @pashj, OCCS/AB is minding the Pilot light.   I asked Nancy to create this issue, and I've also provided her with some boilerplate SPARQL for another request.

**Comment by danizen** [comment]
@pashj, I think the new MeSH On Demand browser was designed to provide a replacement for the current browser, and does not contain APIs, although a simple search feature for Descriptors and D+Q pairs may be present.   OCCS/MLB is not currently working on that to the best of my knowledge because Sukhbir left.

**Comment by fallgrennj** [comment]
It depends on the functionality.
-Nancy

**Comment by nvariant** [comment]
MLB has made it very clear that they are unable to do any work that falls
outside the current workflow.

That prohibition or resource limitation would include enhancements and
improvements to existing products and functionality, as well as things they
consider "new".

In my understanding, they would consider MeSH on Demand and any associated
browser to be "new", and outside the scope of work they are willing to take
on.

That said, I also understand they are working on a MeSH browser to answer
their need to move the current browser off the server it is on. However,
they own that project and are directing it with really no input (so far at
least) from LO. They demoed an early beta prototype back in October I
think, but weren't looking for feature suggestions at that time.

- John

**Comment by danizen** [comment]
Should be internal.
