### ISSUE TITLE
Incomplete data?

### ISSUE THREAD

**Issue by bartgras** [HHS/meshrdf#75]
I've just manually downloaded the data (file mesh.nt) from `ftp.nlm.nih.gov` and loaded to my Virtuoso database.
When I do following query:

```
PREFIX mesh: <http://id.nlm.nih.gov/mesh/>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (COUNT(*) AS ?results) 
WHERE {
   ?s ?p ?o .
}
```

Result is "14715934".

The same query on https://id.nlm.nih.gov/mesh/query , result is "39340424"

I noticed the difference while comparing other queries results, my local database was not returning some Concepts, while https://id.nlm.nih.gov/mesh/query was.

Am I missing something? Do I need to e.g. upload *.nt files from previous years?

**Comment by bjonnh** [comment]
Looking at that, I would say that you need a Reasoner.

**Comment by flamingofugang** [comment]
Once you loaded data into Virtuoso, you need to check the log file to make sure there was no error during loading. I would suggest to try other RDF stores, like Jena TDB, Blazegraph, or trial version Stardog, so you can compare how many triples the file really has.

**Comment by flamingofugang** [comment]
Do single-thread loading rather than parallel, since the later may cause deadlock, and the loading will not be complete.

**Comment by davidanderson3** [comment]
There are multiple graphs available at this endpoint. Use the current graph (see the query below). This should be aligned with mesh.nt, and reflects the current state of MeSH. 

```
PREFIX mesh: <http://id.nlm.nih.gov/mesh/>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (COUNT(*) AS ?results) 
FROM <http://id.nlm.nih.gov/mesh>
WHERE {
   ?s ?p ?o .
}
```

[Some documentation](https://hhs.github.io/meshrdf/versioning-policy.html).

The other graphs available at this endpoint correspond to particular years. You can safely ignore them, unless you're interested in tracking MeSH over time.

**Comment by danizen** [comment]
> Am I missing something? Do I need to e.g. upload *.nt files from previous years?

Yes, that's the cause, but I would suggest you adjust your query as suggested by David above, instead.   The current year or 2017 may be what you want.
